### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by arcadas** [jenssegers/laravel-mongodb-sentry#10]
Please create a new branch or version and change the required Cartalyst\Sentry package in composer.json:

From:
`"cartalyst/sentry": "2.1.*",`
To:
`"cartalyst/sentry": "dev-feature/laravel-5",`

This fix the `Call to undefined method [package]` issue.

Thank You!

**Comment by askmatey** [comment]
:+1:

**Comment by claudkho** [comment]
+1

**Comment by jenssegers** [comment]
Did they still not merge the L5 branch?

**Comment by jenssegers** [comment]
I modified composer.json

**Comment by askmatey** [comment]
Thank you mate

**Comment by tusharvikky** [comment]
Do we have to update this for L4.2?

**Comment by arcadas** [comment]
You can use the following settings in your composer.json file for Laravel 4:

``` js
"jenssegers/mongodb-sentry": "dev-master#52c12d5d18d3fc35376d735fcef7fd48fce8b4f3"
```

**Comment by tusharvikky** [comment]
@arcadas we still have to update this?

```
"cartalyst/sentry": "dev-feature/laravel-5",
```

**Comment by arcadas** [comment]
If you update your composer.json and run `composer update`, then the 
`"cartalyst/sentry": "dev-feature/laravel-5",` 
will be change to 
`"cartalyst/sentry": "2.1.*",` 
in the `vendor/jenssegers/mongodb-sentry/composer.json`.

**Comment by tusharvikky** [comment]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jenssegers/mongodb-sentry dev-master#52c12d5d18d3fc35376d735fcef7fd48fce8b4f3 -> satisfiable by jenssegers/mongodb-sentry[dev-master].
    - jenssegers/mongodb-sentry dev-master requires cartalyst/sentry dev-feature/laravel-5 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

```

**Comment by arcadas** [comment]
Did you set minimum-stability to dev? `"minimum-stability": "dev"`

**Comment by tusharvikky** [comment]
```
Call to undefined method Cartalyst\Sentry\SentryServiceProvider::mergeConfigFrom() 
```

EDIT: The composer.json of `vendor/jenssegers/mongodb-sentry` requires sentry:2.1, But its pulling dev-feature/laravel-5.

**Comment by tusharvikky** [comment]
![image](https://cloud.githubusercontent.com/assets/1810991/6769932/a7d165c6-d0d5-11e4-9f04-dd28405c37b8.png)

**Comment by jenssegers** [comment]
I tagged v1.1.0-beta. Will tag v1.1.0 once they merge it into master.
