### ISSUE TITLE
Laravel 4 breaks after L5 support

### ISSUE THREAD

**Issue by tusharvikky** [jenssegers/laravel-mongodb-sentry#11]
After `"jenssegers/mongodb-sentry": "dev-master#52c12d5"`, 
composer still fetching `cartalyst/sentry (dev-feature/laravel-5 5e5e232)`

EDIT:
https://getcomposer.org/doc/04-schema.md#package-links

Please create a tag for L4.

**Comment by jenssegers** [comment]
I create v1.0.1, if you use that in composer it should work.
